### ISSUE TITLE
Incorrect comment about measurement ranges for ADC

### ISSUE THREAD

**Issue by thedevleon** [esp-rs/esp-hal#1229]
According to the comments on the [Attenuation enum](https://github.com/esp-rs/esp-hal/blob/bfb530d3a3d1ef60c175e2687df9bd3241092a25/esp-hal/src/analog/adc/mod.rs#L33) for setting an ADC, the maximum range I should be getting with `Attenuation11dB` is `0-2600mV`. However, this does not line up with the datasheet (i.e. of the esp32c6), and testing with a variable power supply, I am getting values of up to 3300mV (as expected) on an ESP32-C6. 

See also the relevant section in the datasheet of the C6:
![image](https://github.com/esp-rs/esp-hal/assets/12817042/7e6e9aae-b6db-407b-832e-6edb7b02bb70)

Maybe this was written with a different SoC? Are the measurement ranges different per SoC?

**Comment by bjoernQ** [comment]
I guess the comment is a copy from esp-idf - it _was_ mentioned in the docs - e.g. here: https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32c3/api-reference/peripherals/adc.html#adc-attenuation but seems it's removed from the docs now

Probably those comments need to get removed completely and instead we should mention the datasheet since apparently those ranges are different per SOC
