### ISSUE TITLE
We've exceeded the concurrency limit for GitHub Actions

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#1644]
We are limited to [20 concurrent jobs](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration), meaning that any additional jobs will be queued until a runner is available. This will obviously drag out the total runtime of the workflow, and we should consider restructuring things.

**Comment by jessebraham** [comment]
With #1658 merged there are unfortunately now an additional 7 jobs to deal with.

**Comment by bjoernQ** [comment]
Yes - that's why I initially didn't add CI in #1658 

Only thing I can think of would be to handle multiple chips in one job. 

e.g. let the xtask take a "chips" argument which populates features and target from that

Downside would be that we don't immediately see for which target the build failed but on the other hand that information is just one click away
