### ISSUE TITLE
How to override the default post_init function?

### ISSUE THREAD

**Issue by konsulten** [esp-rs/esp-hal#1698]
Currently it seems the watchdogs are disabled by default in the __post_init function. Is there a possibility to override or modify this behaviour?

https://github.com/esp-rs/esp-hal/pull/763

**Comment by Dominaezzz** [comment]
I'm pretty sure you can just re-enable the watchdog in your main function. There should be an example as well.

**Comment by konsulten** [comment]
Won’t there be some time where its disabled then? I would prefer never to
disable it

ons 19 juni 2024 kl. 22:26 skrev Dominic Fischer ***@***.***>:

**Comment by MabezDev** [comment]
We'd probably add this behind a configuration option. We don't have a complete story for this yet see #1111.

**Comment by Dominaezzz** [comment]
For this sort of thing, rather than a config option, which can only be specified once per crate. This should probably be part of the entry macro, which can be specified once per application/binary (of which there could be multiple in a crate).

```Rust
#[entry(watchdog, psram(80))]
fn main() {
    // stuff
}
```

> I would prefer never to disable it

Not that I think this is bad to want or something, I'm just curious what you're worried about happening between the disable and re-enable? Or is this a matter of principal?

**Comment by konsulten** [comment]
Im worried that I have made a bad OTA image and get stuck in it :/

ons 19 juni 2024 kl. 22:53 skrev Dominic Fischer ***@***.***>:

**Comment by MabezDev** [comment]
With the changes to how we initialize the hal, we can now make this a global configuration option. (Bear in mind this issue on the esp32 when implementing: https://github.com/esp-rs/esp-hal/issues/2105)
