### ISSUE TITLE
Question about trait `CreateErasedPin` being `#[doc(hidden)]`

### ISSUE THREAD

**Issue by ROMemories** [esp-rs/esp-hal#1799]
As part of providing a higher-level abstraction, I'm trying to write a function that would internally instantiate a [`gpio::AnyInput`](https://docs.esp-rs.org/esp-hal/esp-hal/0.18.0/esp32c6/esp_hal/gpio/struct.AnyInput.html). However, [its constructor](https://docs.esp-rs.org/esp-hal/esp-hal/0.18.0/esp32c6/esp_hal/gpio/struct.AnyInput.html#method.new) requires the passed peripheral to implement `CreateErasedPin`.
That trait not being part of `esp-hal`'s documentation, as it is marked `#[doc(hidden)]`, I was wondering whether that was only to simplify documentation, or whether that was meant to exclude this trait from the SemVer commitment of `esp-hal`.

https://github.com/esp-rs/esp-hal/blob/7ea471c1ac2b7fbb4468a3f4211225e5dec2fe5c/esp-hal/src/gpio/mod.rs#L397-L400

Is it ok to reference this trait in my function's list of bounds (so I am able to call `AnyInput::new()` in it), or could this be broken later by a change of `esp-hal`'s API? Or is there a better way of doing this?

**Comment by bjoernQ** [comment]
We are still refining the API for usability and in general there where and will be breaking changes for now.

The fact the trait is doc-hidden is definitely to make the docs more readable since most users won't care much about those traits. Currently it's not planned to remove that trait but if we consider another solution as a better option, we might change code there. We usually provide migration guides with every release but in this case (since it's doc-hidden) we probably won't.

I don't know enough about your code to suggest alternatives unfortunately - depending on what exactly you are trying to achieve maybe taking `AnyInput` and let the user create them might be more future proof but as said I really don't know enough about your code.
