### ISSUE TITLE
Linker script appears to not match the comments

### ISSUE THREAD

**Issue by TheButlah** [esp-rs/esp-hal#205]
I am new to linker scripts, but as I was reading through the `db-esp32c3-memory.x`, I saw [line 7](https://github.com/esp-rs/esp-hal/blob/5054681ba3a7333666e4685df05c2554625ff835/esp32c3-hal/ld/db-esp32c3-memory.x#L7) which states in a comment that the DRAM region goes from `[0x3FC80000, 0x3FCE0000]`, However, [Line 22](https://github.com/esp-rs/esp-hal/blob/5054681ba3a7333666e4685df05c2554625ff835/esp32c3-hal/ld/db-esp32c3-memory.x#L22) states that the length of the DRAM region is `0x50000`, which would mean that dram ends at 0x3FC**D**0000 instead of   0x3FC**E**0000.

Which is the intended ending address for the region? Why does it diverge from the comment?

**Comment by bjoernQ** [comment]
Parts of that upper memory is also used by ROM functions etc. AFAIK. Plus (not really applies here since it's direct-boot) the 2nd stage bootloader uses some memory there that can't be touched before the application starts (i.e. no data should be loaded there by 2nd stage bootloader since it would overwrite its own memory)

**Comment by jessebraham** [comment]
I'm not sure there's really anything actionable here so I'm going to close this. Feel free to re-open if you feel otherwise.
