### ISSUE TITLE
DHCP takes a long time to get an IP address

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#2246]
Sometimes it takes quite long to get an IP address

Apparently, it takes a few Discover messages until my AP sends a Request - with an ESP-IDF example that is not the case:

![image](https://github.com/user-attachments/assets/881baaef-808b-44ac-ad6f-c4f80bafee18)

Here it took five discover messages until I got a request. The next discover+request was from esp-idf

The strangest thing is that the transaction id of the request doesn't match any discover message (but the IP was accepted). For ESP-IDF everything looked normal

I even changed smoltcp to send the exact same request but nothing changed.

It might be something special about my AP (so would be good if others could verify that)

**Comment by bjoernQ** [comment]
Seems like smoltcp will always generate a new transaction ID when it sends a message - which is ok and explains the different transaction id in the request

**Comment by bugadani** [comment]
Is this async? If so, we had a similar problem last year where the embassy-net task wasn't waken.

**Comment by bjoernQ** [comment]
That's using the blocking API to keep the testing as simple as possible

**Comment by AnthonyGrondin** [comment]
From personal experience, I have noticed a different behavior for getting an IP address between two esp32s3.

One is an esp32-s3-mini-1, on a breadboard, and it takes a long time to get connected to wifi and get an IP.
The other is an esp32-s3-wroom-1, mounted on a PCB and it always connects faster and get an IP fast. I assume this is due to an antenna behavior, as the PCB acts as an antenna, so I never looked at the Wireshark trace.

I flashed the `wifi_dhcp` example on both 

Here is the capture for the esp32-s3-mini-1 on a breadboard: 
![image](https://github.com/user-attachments/assets/fe22679d-01e5-4058-a017-e0aa499d5edc)


Here is the capture for the esp32-s3-wroom-1 installed on a PCB:
![image](https://github.com/user-attachments/assets/d39d3326-cfec-4986-b130-3eecc5ee7fd2)

**Comment by bjoernQ** [comment]
I did some more testing - this time using my laptop as an AP


![image](https://github.com/user-attachments/assets/0f9b3131-4f35-4bad-a2b4-d67ec0cc52ae)

Looks exactly the same for blocking and async. Looks very good but then it waits five seconds and sends the request again.
