### ISSUE TITLE
`Event`, `WakeEvent`, `Level`, `Pull`, `DriveStrength` & `AlternateFunction` are missing `#[non_exaustive]`

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-hal#2694]

**Comment by bugadani** [comment]
Event, AlternateFunction, Pull, DriveStrength are complete as far as I can tell. WakeEvent is not, but it's because its intent is wrong: Event covers the options that can wake up the MCU from light sleep, WakeEvent is closer to deep sleep as far as I can tell. As we don't intend to stabilize the sleep APIs just yet, I don't think we need to do anything about WakeEvent just now.
