### ISSUE TITLE
#263 made `I2C::new()` infallible

### ISSUE THREAD

**Issue by dimpolo** [esp-rs/esp-hal#278]
Both `i2c::SetupError::InvalidClkConfig` and `i2c::SetupError::PeripheralDisabled` aren't used anywhere.

Would you welcome a PR removing this Error and changing `I2C::new`?

**Comment by bjoernQ** [comment]
Sorry - somehow, I didn't notice this one - I guess `PeripheralDisabled` is definitely something to remove - `InvalidClkConfig` might be something we should re-introduce but since it's currently not there we can also remove it for now and re-introduce it once the constructor will actually use it

So yes - a PR like that is welcome

**Comment by dimpolo** [comment]
Nothing to be sorry about :)
