### ISSUE TITLE
Implement the `embedded_hal_async::delay::DelayUs` trait

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-hal#752]
[This trait](https://docs.rs/embedded-hal-async/1.0.0-rc.1/embedded_hal_async/delay/trait.DelayUs.html) as added in one of the alpha releases, and we never implemented it. This trait will need to be implemented in order to use future versions of `embassy`.

- [x] `SYSTIMER` (#812)
- [ ] `TIMG`
- [ ] Xtensa CPU Timers (?)

**Comment by MabezDev** [comment]
This trait has been around since the 0.1 release of the eha, but didn't really need to implement it as embassy-time offers an impl based on the time driver impls. If we were to implement this we should impl on the following

- Systimer (alarms only)
- TIMG timers
- Xtensa internal CPU timers (maybe)
- Anything else that has a configurable time period + interrupt? Maybe something in the RTC domain

**Comment by jessebraham** [comment]
Once https://github.com/esp-rs/esp-hal/issues/1063 is solved we can revisit this issue.

**Comment by jessebraham** [comment]
This trait is implemented for `SYSTIMER` directly, and is additionally implemented for `OneShotTimer`; since the `timer::timg` module still does not contain an `asynch` module of its own, I'm just going to close this as "completed".
