### ISSUE TITLE
System peripheral does not exist anymore?

### ISSUE THREAD

**Issue by MatthijsReyers** [esp-rs/esp-hal#844]
All examples in the `stm32-hal/examples` folder use the `peripherals.SYSTEM` peripheral, but the compiler claims `SYSTEM` does not exist. 
Are these examples simply horribly out of date or am I misunderstanding something?

For reference, here is a minimal example that does not compile:

*main.rs*
```rs
#![no_std]
#![no_main]

use esp_backtrace as _;
use esp32_hal::{
    peripherals::Peripherals, 
    prelude::*, 
};

#[entry]
fn main() -> ! {
    let peripherals = Peripherals::take();
    let mut system = peripherals.SYSTEM.split();
    loop {}
}
```

*Cargo.toml*
```toml
[package]
name = "demo"
edition = "2021"

[dependencies]
esp32-hal = "0.15.0"
esp-backtrace = { version = "0.8.0", features = ["esp32", "panic-handler", "exception-handler", "print-uart"] }
```

Error:
```
   Compiling demo v0.1.0 (/home/matt/School/Design project/counter-firmware/counter-firmware)
error[E0609]: no field `SYSTEM` on type `Peripherals`
  --> src/main.rs:13:34
   |
13 |     let mut system = peripherals.SYSTEM.split();
   |                                  ^^^^^^ unknown field
   |
   = note: available fields are: `AES`, `APB_CTRL`, `BB`, `DPORT`, `EFUSE` ... and 40 others

For more information about this error, try `rustc --explain E0609`.
error: could not compile `demo` (bin "demo") due to previous error
```

**Comment by jessebraham** [comment]
The ESP32 has a peripheral called `DPORT`, the ESP32-C6/H2 have one called `PCR`, and the other chips call it `SYSTEM`. Because of this we have aligned the peripheral names in the HAL to all use `SYSTEM`, however this is a recent change and has not yet been published.

Referring to the [documentation](https://docs.rs/esp32-hal/latest/esp32_hal/peripherals/index.html) for the published version of the HAL (which you are using) shows that this peripheral is still named `DPORT`.

Once we publish new releases of the HALs these peripherals names will all be aligned to `SYSTEM`, as they currently are in the `main` branch.
